#!/bin/bash

if [ -e $1 ]; then
echo -n > $1
echo find -name $1
echo "Такой файл уже существует, очистка..."
else
  echo >> $1
echo "Создан новый файл $1"
fi

echo "Пользователь: $USER"
echo "UID: $UID"

for (( i=1; i<=$2; i++))
do
echo "Строка $i" >> $1
done

echo file $1" заполнен строками ($2)"
